name: flutter_launcher_icons_maker
description: A package which simplifies the task of updating your Flutter app's launcher icon.
version: 0.0.0
maintainer: Jonathan Gao
homepage: https://github.com/gsmlg-dev/flutter_launcher_icons_maker

dependencies:
  args: ^2.3.2
  checked_yaml: ^2.0.2
  cli_util: ^0.4.0
  image: ^4.0.15
  json_annotation: ^4.8.0
  path: ^1.8.2
  yaml: ^3.1.1

environment:
  sdk: ">=2.15.1 <4.0.0"

dev_dependencies:
  # Needed by build_version
  build_runner: ^2.3.3
  # https://pub.dev/packages/build_version
  build_version: ^2.1.1
  json_serializable: ^6.6.1
  mockito: ^5.3.2
  test: ^1.23.1
  test_descriptor: ^2.0.1
